export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FILTER_REQUEST_ITEMS = 'FILTER_REQUEST_ITEMS';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';

export const FETCH_WORKGROUP = 'FETCH_WORKGROUP';
export const FETCH_WORKGROUPS = 'FETCH_WORKGROUPS';
export const FETCH_WORKGROUPS_BY_REQUEST_ID = 'FETCH_WORKGROUPS_BY_REQUEST_ID';
export const FETCH_REQUESTS_BY_WORKGROUP_ID = 'FETCH_REQUESTS_BY_WORKGROUP_ID';

export const ADD_TO_WORKGROUP = 'ADD_TO_WORKGROUP';
export const ADD_WORKGROUP = 'ADD_WORKGROUP';
export const UPDATE_WORKGROUP = 'UPDATE_WORKGROUP';
export const REMOVE_WORKGROUP = 'REMOVE_WORKGROUP';
