export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const UPDATE_REQUEST = 'FETCH_REQUEST';
export const FETCH_STAGES_FOR_REQUEST = 'FETCH_STAGES_FOR_REQUEST';

export const FETCH_WORKFLOW = 'FETCH_WORKFLOW';
export const FETCH_WORKFLOWS = 'FETCH_WORKFLOWS';

export const ADD_WORKFLOW = 'ADD_WORKFLOW';
export const UPDATE_WORKFLOW = 'UPDATE_WORKFLOW';
export const REMOVE_WORKFLOW = 'REMOVE_WORKFLOW';

export const FETCH_RBAC_GROUPS = 'FETCH_RBAC_GROUPS';
export const FETCH_RBAC_GROUP = 'FETCH_RBAC_GROUP';
