export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_CONTENT = 'FETCH_REQUEST_CONTENT';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';

export const EXPAND_REQUEST = 'EXPAND_REQUEST';

export const CREATE_REQUEST_ACTION = 'CREATE_REQUEST_ACTION';
export const FETCH_WORKFLOW = 'FETCH_WORKFLOW';
export const FETCH_WORKFLOWS = 'FETCH_WORKFLOWS';

export const ADD_WORKFLOW = 'ADD_WORKFLOW';
export const UPDATE_WORKFLOW = 'UPDATE_WORKFLOW';
export const REMOVE_WORKFLOW = 'REMOVE_WORKFLOW';
export const REMOVE_WORKFLOWS = 'REMOVE_WORKFLOWS';

export const EXPAND_WORKFLOW = 'EXPAND_WORKFLOW';

export const FETCH_RBAC_GROUPS = 'FETCH_RBAC_GROUPS';
export const FETCH_GROUP_NAMES = 'FETCH_GROUP_NAMES';

export const SET_OPENAPI_SCHEMA = 'SET_OPENAPI_SCHEMA';
export const SET_USER_ACCESS = 'SET_USER_ACCESS';

